id: I8F0E298F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-13T03:07:43+00:00'
last_modified: '2022-06-15T16:35:28.927631+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24016
  title: བོད་ཀྱི་གཏམ་དཔེ་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9BCC:
      image_group_id: I1KG24073
      title: Volume 1 of bod kyi gtam dpe phyogs bsgrigs/
      total_pages: 310
      order: 1
      base_file: 9BCC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
